config/routes.rb
Rails.application.routes.draw do
  #devise_for :admins
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_scope :admin do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_admin_registration" # custom path to sign_up/registration
  end

  devise_for :admins, :skip => [:registrations]
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
  end

  root to: "welcome#index"
  get 'result', to: 'welcome#result'
  get 'marathons', to: 'welcome#marathons'
  get 'certificates', to: 'welcome#certificates'
  get 'download_pdf', to: "welcome#download_pdf"
  get 'download_zip', to: "welcome#download_zip"
  get 'zip_zip', to: "welcome#zip_zip"

  #resources :users, only: [:index, :show, :edit], param: :email, :constraints => { :email => /.*/ } do
  #resources :users, param: :email, :constraints => { :email => /.*/ } do
  #  get 'download_pdf', to: "users#download_pdf"
  #  get 'download_zip', to: "users#download_zip"
  #end

  #resources :certificates
  #resources :rus_templates
  #resources :eng_templates


  #get 'download_pdf', to: "users#download_pdf"

  namespace :admin do
    root 'admin#dashboard'
    resources :users

    resources :marathons do
      member do
        patch 'delete_all_users', to: 'marathons#delete_all_users'
      end
    end

    resources :lectures
    resources :certificates
    resources :rus_templates
    resources :eng_templates
    resources :tables do
      member do
        patch 'create_users', to: 'tables#create_users'
        patch 'renew', to: 'tables#renew'
      end
    end
    get 'download_one_pdf', to: "users#download_one_pdf"
    get 'download_all_pdfs', to: "users#download_all_pdfs"
  end

end

app/controllers/welcome_controller.rb
require('zip')
class WelcomeController < ApplicationController

  before_action :type_device

  def index
    if params[:email]
      #redirect_to user_path(params[:email])
      user = User.find_by_email(params[:email].to_s.downcase)
      if user
        # redirect_to result_path(email: params[:email].to_s.downcase)
        redirect_to marathons_path(email: params[:email].to_s.downcase)
      else
        flash.now[:danger] = 'Ooops! Are you sure you entered the correct email address?'
        render action: :index
      end
    end
  end

  def result
    @user = User.find_by_email(params[:email])

    if @user.language == 'rus'
      @hi =           'Привет'
      @chose =        'Здесь ты можешь выбрать тот сертификат, который тебе нужен или скачать их все сразу'
      @speaker =      'Спикер'
      @description =  'Описание'
      @date =         'Дата'
      @download =     'Скачать'
      @no_certs =     'Нет доступных сертификатов. Пожалуста, обратитесь в службу поддержки.'
      @main =         'На главную'
      @download_all = 'Скачать все'
    else
      @hi =           'Hi'
      @chose =        'Here you can choose the certificate you need or download them all at once'
      @speaker =      'Speaker'
      @description =  'Description'
      @date =         'Date'
      @download =     'Download'
      @no_certs =     'No certificates available. Please contact support.'
      @main =         'Back to Main'
      @download_all = 'Download all'
    end

  end

  def download_pdf
    user = User.find_by_email(params[:user_email])
    certificate = Certificate.find(params[:certificate_id])
    send_data(user.generate_cert_with_prawn(certificate), filename: "#{certificate.name}_cert.pdf", type: 'application/pdf')
  end

  def download_zip
    user = User.find_by_email(params[:user_email])
    filename = 'all_certs_archive.zip'
    zip_file = Tempfile.new(filename)
    begin
      Certificate.scope_by_language(user.language).each do |type|
        cert = Tempfile.new("#{type.name}-#{user.email}.pdf")
        cert.binmode
        cert.write(user.generate_cert_with_prawn(type))
        Zip::File.open(zip_file.path, Zip::File::CREATE) do |zip|
          zip.add("#{type.name}-#{user.email}.pdf", cert.path)
        end
        cert.close
        cert.unlink
      end
      zip_data = File.read(zip_file.path)
      zip_file.unlink
      send_data(zip_data, type: 'application/zip', disposition: 'attachment', filename: filename)
    end
  end

  def zip_zip
    user = User.find_by_email(params[:user_email])
    filename = 'all_certs_archive.zip'
    certs_files = user.generate_all_certs
    certs_files.rewind
    send_data(certs_files.read, type: 'application/zip', disposition: 'attachment', filename: filename)
  end


  def marathons
    @email = params[:email]
    @users = User.where(email: params[:email])
    @mars = Marathon.where(id: @users.pluck(:marathon_id))
  end

  def certificates
    @marathon = Marathon.find params[:marathon_id]
    @user = User.find_by(email: params[:email], marathon: @marathon)
    @certificates = @marathon.lectures

    if @user
      @hi =           'Привет'
      @chose =        'Здесь ты можешь выбрать тот сертификат, который тебе нужен или скачать их все сразу'
      @speaker =      'Спикер'
      @description =  'Описание'
      @date =         'Дата'
      @download =     'Скачать'
      @no_certs =     'Нет доступных сертификатов. Пожалуста, обратитесь в службу поддержки.'
      @main =         'На главную'
      @download_all = 'Скачать все'
    else
      @hi =           'Hi'
      @chose =        'Here you can choose the certificate you need or download them all at once'
      @speaker =      'Speaker'
      @description =  'Description'
      @date =         'Date'
      @download =     'Download'
      @no_certs =     'No certificates available. Please contact support.'
      @main =         'Back to Main'
      @download_all = 'Download all'
    end
  end

end

app/views/welcome/_m_marathon.html.erb
<% @mars.each do |m| %>


  <%#= link_to certificates_path(email: @email, marathon_id: m.id) do %>
  <a href="<%= certificates_path(email: @email, marathon_id: m.id) %>" class="link-border mb-3" style="font-family: Montserrat!important; text-decoration: none;">
    <div class="card" style="width: 100%; background: rgb(255 255 255 / 30%); border: none;">
      <div class="row g-0">
        <div class="col-md-3 d-flex align-items-center">
          <img src="<%= m.logo.url %>" alt="..." style="height: 15em; width: 15em; padding: 16px;">
        </div>
        <div class="col-md-9">
          <div class="card-body">
            <div class="card-body d-flex justify-content-between" style="padding-left: 0">
              <h1 class="card-title"><%= m.name %></h1>
              <div>
                <span  class="btn btn-dark btn-lg" style="border-radius: 16px"> Открыть / open</span>
              </div>
            </div>
            <p class="card-text" style="padding-bottom: 24px; font-size: x-large"><%= m.description %></p>
          </div>
        </div>
      </div>
    </div>
  </a>


  <%# end %>
<% end %>

<div class="container" style="display: flex; justify-content: center; align-items: center; margin-left: auto; margin-right: auto">
  <%= link_to "На главную / back to main", root_path(), class: "btn btn-light btn-lg mb-5 mt-5",
              style: "font-family: Montserrat!important; border-radius: 16px; border:none; background: rgb(255 255 255 / 30%);" %>
</div>

app/views/welcome/_marathon.html.erb
<% @mars.each do |m| %>

  <div class="card text-center" style="font-family: Montserrat!important; min-height: 48rem; width: 24rem; margin: 16px; background: rgb(255 255 255 / 30%); border: none; position: relative;">

    <div>
      <img src="<%= m.logo.url %>" class="card-img-top" style="padding: 16px; " alt="...">
      <div class="card-body mt-3">
        <h3 class="card-title"><%= m.name %></h3>
        <p class="card-text mt-4"><%= m.description %></p>
      </div>
    </div>

    <div class="card-body" style="position: relative;">
      <a href="<%= certificates_path(email: @email, marathon_id: m.id) %>" class="btn btn-dark btn-lg mt-3 mb-4" style="border-radius: 16px"> Открыть / open</a>
    </div>

  </div>

<% end %>

app/views/welcome/certificates.html.erb
<body style="background-image:url(<%= asset_path 'pattern.png'%>); background-size:cover; background-repeat:no-repeat; background-attachment:fixed; height:100%; padding: 0 16px; font-family: Montserrat!important">

  <% fluid = '-fluid' if @device != 'desktop' %>

  <div class="container<%= fluid %> mt-5" style="background: rgb(255 255 255 / 70%); border-radius: 16px; margin-bottom: 36px;">

    <div class="d-flex justify-content-between">
      <div style="padding: 24px">
        <h1 style="padding-top: 16px"><%= "👋 #{@user.firstname}" %>!</h1>
        <p class="text-muted fw-light" style="margin-bottom: 0"><%= 'Здесь ты можешь скачать один сертификат или все сразу /' %></p>
        <p class="text-muted fw-light"><%= 'Here you can download one certificate or all at once' %></p>
      </div>

      <div class="d-flex align-items-center justify-content-center" style="padding: 24px">
        <a class="btn btn-dark" style="border-radius: 16px" href="<%= admin_download_all_pdfs_path(id: @user.id) %>" target="_blank">
          <%#= "ВСЁ / ALL" %>
          <%= "Скачать все / Download all" %>
        </a>
      </div>
    </div>

    <h3 class="text-center mb-3"><%= "#{@marathon.name}" %>!</h3>

    <div style="padding-left: 24px; padding-right: 24px; padding-bottom: 24px;">
    <table class="table table-hover">
      <thead>
      <tr>
        <th scope="col" style="width: 5%;">#</th>
        <th scope="col" style="width: 25%;"><%= "Спикер / speaker" %></th>
        <th scope="col" style="width: 45%;"><%= "Название / name" %></th>
        <th scope="col" style="width: 15%;"><%= "Дата / date" %></th>
        <th scope="col" style="width: 10%; text-align: center"></th>
      </tr>
      </thead>
      <tbody>
      <% @marathon.lectures.each_with_index { |cert, index| %>
        <tr>
          <th scope="row"><%= index + 1 %></th>
          <td><%= cert.speaker %></td>
          <td><%= cert.name %></td>
          <td><%= cert.date.strftime('%d.%m.%y') %></td>
          <td>
            <a class="d-flex align-items-center justify-content-center text-warning" href="<%= admin_download_one_pdf_path(id: @user.id, :lecture_id => cert.id) %>" target="_blank" style="font-size: 24px;">
<!--              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-download" fill="currentColor" xmlns="http://www.w3.org/2000/svg">-->
<!--                <path fill-rule="evenodd" d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>-->
<!--                <path fill-rule="evenodd" d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>-->
<!--              </svg>-->

              <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="dark" class="bi bi-file-earmark-arrow-down-fill" viewBox="0 0 16 16">
                <path d="M9.293 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.707A1 1 0 0 0 13.707 4L10 .293A1 1 0 0 0 9.293 0zM9.5 3.5v-2l3 3h-2a1 1 0 0 1-1-1zm-1 4v3.793l1.146-1.147a.5.5 0 0 1 .708.708l-2 2a.5.5 0 0 1-.708 0l-2-2a.5.5 0 0 1 .708-.708L7.5 11.293V7.5a.5.5 0 0 1 1 0z"/>
              </svg>
            </a>
          </td>
        </tr>
      <% } %>
      </tbody>
    </table>

  </div>

  </div>

  <div class="d-flex justify-content-center">
    <%= link_to "Назад / back", marathons_path(email: @user.email.downcase), class: "btn btn-light btn-lg mb-5",
                style: "border-radius: 16px; border:none; background: rgb(255 255 255 / 30%);" %>
  </div>

</body>

app/views/welcome/index.html.erb
<body style="background-image:url(<%= asset_path 'pattern.png'%>); background-size:cover; background-repeat:no-repeat; background-attachment:fixed; height: 100vh;">


  <div class="container" style="margin:0; height: 100vh; display: flex; justify-content: center; align-items: center; margin-left: auto; margin-right: auto;">
    <div>

      <% if @device == 'desktop' %>

        <h1 class="display-2 text-center" style="font-family: Montserrat">TOP MUA</h1>
        <div class="d-flex align-items-center justify-content-center mt-5" style="font-family: Montserrat!important">
          <%= form_tag root_path(), method: 'get', :class => 'input-group input-group-lg', :style => "width: 40em" do %>
            <%= text_field_tag :email, params[:email], class: 'form-control', type: 'search', style: 'border: none;', placeholder: "e-mail *", autofocus: true, required: true %>
            <div class="input-group-append mb-5">
              <%= submit_tag "Найти", class: 'btn btn-dark' %>
            </div>
          <% end %>
        </div>

      <% else %>

        <h1 class="display-1 text-center" style="font-family: Montserrat;">TOP MUA</h1>
        <div class="d-flex align-items-center justify-content-center mt-5" style="font-family: Montserrat!important">
          <%= form_tag root_path(), method: 'get' do %>
            <%= text_field_tag :email, params[:email], class: "form-control form-control-lg mt-3 mb-3", type: 'search', style: 'width: 20em; height: 3em; border: none; font-size: 2em; border-radius: 1em; padding: 1em', placeholder: "e-mail *", autofocus: true, required: true %>
            <div class="mb-5" style="width: 100%; display: flex; justify-content: center;">
              <%= submit_tag "Найти", class: 'btn btn-lg btn-dark btn-block mt-3', style: 'font-size: 2em; border-radius: 1em; height: 3em;' %>
            </div>
          <% end %>
        </div>

      <% end %>

      <hr class="mt-5">
      <div class="mt-2" style="font-family: Montserrat; color: #2E2F30; font-size: large">
        <p class="fw-lighter">введите адрес электронной почты, который Вы использовали для регистрации участия в конференции </p>
      </div>

    </div>
  </div>

</body>

app/views/welcome/marathons.html.erb
<body style="background-image:url(<%= asset_path 'pattern.png'%>); background-size:cover; background-repeat:no-repeat; background-attachment:fixed; height: 100vh;">
<!--  <div class="container" style="margin:0; height: 80vh; display: flex; justify-content: center;align-items: center; margin-left: auto; margin-right: auto">-->
  <% if @device == 'desktop' %>
    <div class="container mt-5" style="display: flex; justify-content: center; align-items: center; margin-left: auto; margin-right: auto">
      <%= render('welcome/marathon', email: @email) %>
    </div>
  <% else %>
  <div class="container-fluid d-flex flex-column" style="margin: 0; height: 80vh; justify-content: center; align-items: center; margin-left: auto; margin-right: auto">
    <%= render('welcome/m_marathon', email: @email) %>
  </div>
  <% end %>
  <% if @device == 'desktop' %>
  <div class="container" style="display: flex; justify-content: center; align-items: center; margin-left: auto; margin-right: auto">
    <%= link_to "На главную / back to main", root_path(), class: "btn btn-light btn-lg mb-5 mt-5",
                style: "border-radius: 16px; border:none; background: rgb(255 255 255 / 30%);" %>
  </div>
<% end %>
</body>

app/views/welcome/result.html.erb
<body style="background-image:url(<%= asset_path 'pattern.png'%>); background-size:cover; background-repeat:no-repeat; background-attachment:fixed; height:100%;">
<div class="container mt-5" style="background: rgb(255 255 255 / 70%); border-radius: 16px; margin-bottom: 72px;">


  <div class="d-flex justify-content-between">
    <div>
      <h1 style="padding-top: 16px"><%= @hi %>, <%= @user.firstname %>!</h1>

      <% if Certificate.scope_by_language(@user.language).any?%>
<!--        <h6 class="text-muted mb-5"><%#= @chose %>-->
<!--          <a href="<%#= download_zip_path(user_email: @user.email) %>" target="_blank" style="font-size: 24px;">-->
<!--            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-earmark-zip" fill="currentColor" xmlns="http://www.w3.org/2000/svg">-->
<!--              <path d="M4 0h5.5v1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V4.5h1V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2z"/>-->
<!--              <path d="M9.5 3V0L14 4.5h-3A1.5 1.5 0 0 1 9.5 3z"/>-->
<!--              <path fill-rule="evenodd" d="M5 7.5a1 1 0 0 1 1-1h1a1 1 0 0 1 1 1v.938l.4 1.599a1 1 0 0 1-.416 1.074l-.93.62a1 1 0 0 1-1.11 0l-.929-.62a1 1 0 0 1-.415-1.074L5 8.438V7.5zm2 0H6v.938a1 1 0 0 1-.03.243l-.4 1.598.93.62.929-.62-.4-1.598A1 1 0 0 1 7 8.438V7.5z"/>-->
<!--              <path d="M6 1h1.5v1H6zM5 2h1.5v1H5zm1 1h1.5v1H6zM5 4h1.5v1H5zm1 1h1.5v1H6V5z"/>-->
<!--            </svg>-->
<!--          </a>-->
<!--        </h6>-->

        <h6 class="text-muted mb-5"><%= @chose %></h6>
        </div>
        <div class="d-flex align-items-center justify-content-center">
<!--          <a class="btn btn-warning" href="<%#= download_zip_path(user_email: @user.email) %>" target="_blank">-->
            <%#= @download_all %>
<!--          </a>-->
          <a class="btn btn-warning" href="<%= zip_zip_path(user_email: @user.email) %>" target="_blank">
            <%= @download_all %>
          </a>
        </div>

        </div>



        <table class="table table-hover mt-3">
          <thead>
          <tr>
            <th scope="col" style="width: 5%;">#</th>
            <th scope="col" style="width: 25%;"><%= @speaker %></th>
            <th scope="col" style="width: 45%;"><%= @description %></th>
            <th scope="col" style="width: 15%;"><%= @date %></th>
            <th scope="col" style="width: 10%; text-align: center"><%= @download %></th>
          </tr>
          </thead>
          <tbody>
          <% Certificate.scope_by_language(@user.language).each_with_index { |cert, index| %>
            <tr>
              <th scope="row"><%= index + 1 %></th>
              <td><%= @user.language == 'eng' && cert.speaker_eng != '' && cert.speaker_eng != nil ? cert.speaker_eng : cert.speaker %></td>
              <td><%= @user.language == 'eng' && cert.description_eng != '' && cert.description_eng != nil ? cert.description_eng : cert.description %></td>
              <td><%= cert.date.strftime('%d.%m.%y') %></td>
              <td>
                <a class="d-flex align-items-center justify-content-center text-warning" href="<%= download_pdf_path(user_email: @user.email, :certificate_id => cert.id) %>" target="_blank" style="font-size: 24px;">
                  <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-download" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
                    <path fill-rule="evenodd" d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
                  </svg>
                </a>
              </td>
            </tr>
          <% } %>
          </tbody>
        </table>

      <% else %>
      <h6 class="text-muted mb-5"><%= @no_certs %></h6>
      <% end %>


      <%= link_to @main, root_path(), class: "btn btn-outline-secondary mt-3 mb-3" %>

</div>
</div>
</body>