config/routes.rb
Rails.application.routes.draw do
  #devise_for :admins
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_scope :admin do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_admin_registration" # custom path to sign_up/registration
  end

  devise_for :admins, :skip => [:registrations]
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
  end

  root to: "welcome#index"
  get 'result', to: 'welcome#result'
  get 'marathons', to: 'welcome#marathons'
  get 'certificates', to: 'welcome#certificates'
  get 'download_pdf', to: "welcome#download_pdf"
  get 'download_zip', to: "welcome#download_zip"
  get 'zip_zip', to: "welcome#zip_zip"

  #resources :users, only: [:index, :show, :edit], param: :email, :constraints => { :email => /.*/ } do
  #resources :users, param: :email, :constraints => { :email => /.*/ } do
  #  get 'download_pdf', to: "users#download_pdf"
  #  get 'download_zip', to: "users#download_zip"
  #end

  #resources :certificates
  #resources :rus_templates
  #resources :eng_templates


  #get 'download_pdf', to: "users#download_pdf"

  namespace :admin do
    root 'admin#dashboard'
    resources :users

    resources :marathons do
      member do
        patch 'delete_all_users', to: 'marathons#delete_all_users'
      end
    end

    resources :lectures
    resources :certificates
    resources :rus_templates
    resources :eng_templates
    resources :tables do
      member do
        patch 'create_users', to: 'tables#create_users'
        patch 'renew', to: 'tables#renew'
      end
    end
    get 'download_one_pdf', to: "users#download_one_pdf"
    get 'download_all_pdfs', to: "users#download_all_pdfs"
  end

end

app/models/marathon.rb
class Marathon < ApplicationRecord
  has_many :tables, dependent: :destroy
  has_many :users, dependent: :destroy
  has_many :lectures, dependent: :destroy

  validates :pdf_height, presence: true, numericality: { only_integer: true }
  validates :pdf_width, presence: true, numericality: { only_integer: true }
  validates :x_pos, presence: true, numericality: { only_integer: true }
  validates :y_pos, presence: true, numericality: { only_integer: true }
  validates :font_size, presence: true, numericality: { only_integer: true }
  validates :font_color, presence: true
  validates_format_of :font_color, with: /\A^(\d{1,2}|100),(\d{1,2}|100),(\d{1,2}|100),(\d{1,2}|100)$\z/i, on: [:create, :update]

  after_save :update_users_name_pdf

  has_attached_file :logo, styles: { :medium => ["500x500>", :png] }
  validates_attachment :logo, presence: true,
                       size: { in: 0..1000.kilobytes },
                       content_type: { content_type: [ 'image/gif', 'image/png', 'image/x-png', 'image/jpeg', 'image/pjpeg', 'image/jpg' ] },
                       message: 'Only Image files are allowed'


  def get_resolution
    "#{pdf_width}х#{pdf_height}"
  end

  def get_percent_done
    return 0 if users.empty?
    (users.already_done.count * 100.0 / users.count).round(2)
  end

  private

  def update_users_name_pdf
    return if (saved_changes.keys & %w[x_pos y_pos font_size font_color pdf_width pdf_height]).empty?
    users.map(&:generate_name_pdf)
  end

end

app/controllers/admin/marathons_controller.rb
class Admin::MarathonsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @marathons = Marathon.all
  end

  def new
    @marathon = Marathon.new
  end

  def create
    @marathon = Marathon.create(marathon_params)

    if @marathon.save
      flash[:success] = "New Marathon successfully created!"
      redirect_to admin_marathons_path
    else
      flash.now[:danger] = "Ooops! Something went wrong! #{@marathon.errors.full_messages.to_sentence}"
      render :new
    end
  end

  def show
    @marathon = Marathon.find(params[:id])
    @tables = @marathon.tables
    @lectures = @marathon.lectures
  end

  def edit
    @marathon = Marathon.find(params[:id])
  end

  def destroy
    @marathon = Marathon.find(params[:id])
    if @marathon.destroy
      flash[:success] = "Marathon was successfully deleted!"
      redirect_to admin_marathons_path
    else
      flash[:danger] = 'Ooops! Something went wrong!'
      render action: :show
    end
  end

  def update
    @marathon = Marathon.find(params[:id])
    if @marathon.update(marathon_params)
      flash[:success] = "Marathon updated!"
      redirect_to admin_marathon_path(@marathon)
    else
      flash.now[:danger] = "Ooops! Something went wrong! #{@marathon.errors.full_messages.to_sentence}"
      render action: :edit
    end
  end

  def delete_all_users
    @marathon = Marathon.find(params[:id])
    @marathon.users.destroy_all
    flash.now[:success] = "Yeeeaahh! All users were successfully deleted!"
    @tables = @marathon.tables
    @lectures = @marathon.lectures
    redirect_to admin_marathon_path(@marathon)
  rescue StandardError => error
    flash.now[:danger] = "Ooops! Something went wrong! #{error.to_sentence}"
    render action: :show
  end

  private

  def marathon_params
    params.require(:marathon).permit(:name, :x_pos, :y_pos, :font_size, :font_color, :pdf_width,
                                     :pdf_height, :description, :logo)
  end

end

app/views/admin/marathons/edit.html.erb
<div class="container mt-5">
  <h1>Edit Marathon#<%= @marathon.id %></h1>
  <p class="text-muted">All fields are required</p>

  <div class="alert alert-warning" role="alert">
    <h6>Если Вы уже создали пользователей для этого Марафона, НЕ МЕНЯЙТЕ здесь следующие параметры:</h6>
    <h6 class="mb-2">Это обновление будет связано со всеми пользователями и займет много времени</h6>
    <hr>
    <p style="margin-bottom: 0;">1. Разерешение pdf-файлов, который будут использоваться как шаблоны сертификатов ('PDF width' и 'PDF height')</p>
    <p style="margin-bottom: 0;">2. Расположение текста в шаблонах сертификатов ('X-pos' и 'Y-pos')</p>
    <p style="margin-bottom: 0;">3. Размер и цвет текста ('Font size' и 'Font color')</p>
  </div>



  <%= form_for @marathon, url: admin_marathon_path do |f| %>

    <h5 class="mt-5 mb-3 text-center">Общая информация</h5>
    <div class="row" style="width: 100%;">

      <div class="col-sm-8 justify-content-center" style="align-items: center; display: flex; flex-direction: column;">
        <div class="form-group" style="width: 100%;">
          <%= f.label :name, "Name:", class: "col control-label" %>
          <div class="col">
            <%= f.text_field :name, required: true, class: "form-control" %>
          </div>
        </div>
        <div class="form-group" style="width: 100%;">
          <%= f.label :description, "Description:", class: "col control-label" %>
          <div class="col">
            <%= f.text_area :description, placeholder: 'Description', required: true, class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="col-sm-4" style="width: 100%; border: 1px solid #ced4da; border-radius: .25rem; padding: 16px;">

        <div class="form-group justify-content-center" style="align-items: center; display: flex; flex-direction: column;">
          <img src="<%= @marathon.logo.url %>" alt="..." style="height: 15em; width: 15em; padding: 16px;">
        </div>

        <div class="input-group">
          <span class="input-group-append">
            <span class="btn btn-secondary" style="border: none; border-top-left-radius: .25rem; border-bottom-left-radius: .25rem" onclick="$(this).parent().find('input[type=file]').click();">Browse</span>
              <%= f.file_field :logo, onchange: "$(this).parent().parent().find('.form-control').html($(this).val().split(/[\\\\|/]/).pop());", style: "display: none;" %>
            </span>
          <span type="text" class="form-control"></span>
        </div>
        <%#= f.file_field :logo, class: "form-control", type: "file", id: "formFile", style: "border: none" %>
      </div>

    </div>

    <table class="table table-borderless table-hover mt-5">
      <tbody >
        <tr>
          <td style="width: 30%; vertical-align: middle;"><h6>Разрешение шаблонов</h6></td>
          <td style="width: 35%; vertical-align: middle;">
            <div class="row">
              <div class="col-sm-6">
                <%= f.label :pdf_width, "PDF width:" %>
              </div>
              <div class="col-sm-6">
                <%= f.text_field :pdf_width, required: true, class: "form-control" %>
              </div>
            </div>
          </td>

          <td style="width: 35%; vertical-align: middle;">
            <div class="row">
              <div class="col-sm-6">
                <%= f.label :pdf_height, "PDF height:" %>
              </div>
              <div class="col-sm-6">
                <%= f.text_field :pdf_height, required: true, class: "form-control" %>
              </div>
            </div>
          </td>
        </tr>

        <tr>
          <td style="width: 30%; vertical-align: middle;"><h6>Расположение текста</h6></td>
          <td style="width: 35%; vertical-align: middle;">
            <div class="row">
              <div class="col-sm-6">
                <%= f.label :x_pos, "X-pos:" %>
              </div>
              <div class="col-sm-6">
                <%= f.text_field :x_pos, required: true, class: "form-control" %>
              </div>
            </div>
          </td>
          <td style="width: 35%; vertical-align: middle;">
            <div class="row">
              <div class="col-sm-6">
                <%= f.label :y_pos, "Y-pos:" %>
              </div>
              <div class="col-sm-6">
                <%= f.text_field :y_pos, required: true, class: "form-control" %>
              </div>
            </div>
          </td>
        </tr>
        <tr>
          <td style="width: 30%;"><h6>Размер и цвет текста</h6></td>
          <td style="width: 35%; vertical-align: middle;">
            <div class="row">
              <div class="col-sm-6">
                <%= f.label :font_size, "Font size:" %>
              </div>
              <div class="col-sm-6">
                <%= f.text_field :font_size, required: true, class: "form-control" %>
              </div>
            </div>
          </td>
          <td style="width: 35%; vertical-align: middle;">
            <div class="row">
              <div class="col-sm-6">
                <%= f.label :font_color, "Font color:" %>
              </div>
              <div class="col-sm-6">
                <%= f.text_field :font_color, required: true, class: "form-control" %>
              </div>
            </div>
          </td>
        </tr>
      </tbody>
    </table>

    <div class="form-group mt-5 ml-3">
      <%= link_to "back", admin_marathon_path(@marathon), class: "btn btn-light" %>
      <%= f.submit class: "btn btn-outline-secondary" %>
    </div>

  <% end %>

</div>

app/views/admin/marathons/index.html.erb
<div class="container mt-5">
  <div class="d-flex align-items-center justify-content-between">
    <h1>All Marathons</h1>
    <%= link_to 'Create new', new_admin_marathon_path(), class: "btn btn-outline-primary btn-sm" %>
  </div>

  <table class="table table-hover mt-3">
    <thead>
    <tr>
      <th scope="col" style="width: 10%; text-align: center">#</th>
      <th scope="col" style="width: 50%;">Name</th>
      <th scope="col" style="width: 10%; text-align: center">Tables</th>
      <th scope="col" style="width: 10%; text-align: center">Users</th>
      <th scope="col" style="width: 10%; text-align: center">Lectures</th>
<!--      <th scope="col" style="width: 20%; text-align: center">State</th>-->
      <th scope="col" style="width: 10%; text-align: center"></th>
    </tr>
    </thead>
    <tbody>

    <% @marathons.each_with_index { |marathon, index|  %>
      <%# table.state == 'new' ? class_name = 'primary' : class_name = table.state %>
      <tr>
        <th scope="row" style="text-align: center"><%= index + 1 %></th>
        <td><%= marathon.name %></td>
        <td style="text-align: center"><%= marathon.tables.count %></td>
        <td style="text-align: center"><%= marathon.users.count %></td>
        <td style="text-align: center"><%= marathon.lectures.count %></td>
<!--        <td style="text-align: center"><span class="badge badge-<%#= class_name %>"><%#= table.state %></span></td>-->
        <td style="text-align: center"><%= link_to "Show", admin_marathon_path(marathon), class: "btn btn-outline-secondary btn-sm" %></td>
      </tr>
    <% } %>
    </tbody>
  </table>






</div>

app/views/admin/marathons/new.html.erb
<div class="container mt-5">
  <h1>Create new Marathon</h1>
  <h6 class="mb-5">All fields are required (except Lastname)</h6>


  <%= form_for @marathon, url: admin_marathons_path do |f| %>

    <h5 class="mt-5 mb-3 text-center">Общая информация</h5>
    <div class="row" style="width: 100%;">

      <div class="col-sm-8 justify-content-center" style="align-items: center; display: flex; flex-direction: column;">
        <div class="form-group" style="width: 100%;">
          <%= f.label :name, "Name:", class: "col control-label" %>
          <div class="col">
            <%= f.text_field :name, required: true, class: "form-control" %>
          </div>
        </div>
        <div class="form-group" style="width: 100%;">
          <%= f.label :description, "Description:", class: "col control-label" %>
          <div class="col">
            <%= f.text_area :description, placeholder: 'Description', required: true, class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="col-sm-4" style="width: 100%; border: 1px solid #ced4da; border-radius: .25rem; padding: 16px;">

        <div class="form-group justify-content-center" style="align-items: center; display: flex; flex-direction: column;">
          <img src="<%= asset_path('add_picture.png') %>" alt="..." style="height: 15em; width: 15em; padding: 16px;">
        </div>

        <div class="input-group">
          <span class="input-group-append">
            <span class="btn btn-secondary" style="border: none; border-top-left-radius: .25rem; border-bottom-left-radius: .25rem" onclick="$(this).parent().find('input[type=file]').click();">Browse</span>
            <%= f.file_field :logo, onchange: "$(this).parent().parent().find('.form-control').html($(this).val().split(/[\\\\|/]/).pop());", style: "display: none;" %>
            </span>
          <span type="text" class="form-control"></span>
        </div>
        <%#= f.file_field :logo, class: "form-control", type: "file", id: "formFile", style: "border: none" %>
      </div>

    </div>

    <table class="table table-borderless table-hover mt-5">
      <tbody >
      <tr>
        <td style="width: 30%; vertical-align: middle;"><h6>Разрешение шаблонов</h6></td>
        <td style="width: 35%; vertical-align: middle;">
          <div class="row">
            <div class="col-sm-6">
              <%= f.label :pdf_width, "PDF width:" %>
            </div>
            <div class="col-sm-6">
              <%= f.text_field :pdf_width, required: true, class: "form-control" %>
            </div>
          </div>
        </td>

        <td style="width: 35%; vertical-align: middle;">
          <div class="row">
            <div class="col-sm-6">
              <%= f.label :pdf_height, "PDF height:" %>
            </div>
            <div class="col-sm-6">
              <%= f.text_field :pdf_height, required: true, class: "form-control" %>
            </div>
          </div>
        </td>
      </tr>

      <tr>
        <td style="width: 30%; vertical-align: middle;"><h6>Расположение текста</h6></td>
        <td style="width: 35%; vertical-align: middle;">
          <div class="row">
            <div class="col-sm-6">
              <%= f.label :x_pos, "X-pos:" %>
            </div>
            <div class="col-sm-6">
              <%= f.text_field :x_pos, required: true, class: "form-control" %>
            </div>
          </div>
        </td>
        <td style="width: 35%; vertical-align: middle;">
          <div class="row">
            <div class="col-sm-6">
              <%= f.label :y_pos, "Y-pos:" %>
            </div>
            <div class="col-sm-6">
              <%= f.text_field :y_pos, required: true, class: "form-control" %>
            </div>
          </div>
        </td>
      </tr>
      <tr>
        <td style="width: 30%;"><h6>Размер и цвет текста</h6></td>
        <td style="width: 35%; vertical-align: middle;">
          <div class="row">
            <div class="col-sm-6">
              <%= f.label :font_size, "Font size:" %>
            </div>
            <div class="col-sm-6">
              <%= f.text_field :font_size, required: true, class: "form-control" %>
            </div>
          </div>
        </td>
        <td style="width: 35%; vertical-align: middle;">
          <div class="row">
            <div class="col-sm-6">
              <%= f.label :font_color, "Font color:" %>
            </div>
            <div class="col-sm-6">
              <%= f.text_field :font_color, required: true, class: "form-control" %>
            </div>
          </div>
        </td>
      </tr>
      </tbody>
    </table>

    <div class="form-group mt-5 ml-3">
      <%= link_to "back", admin_marathons_path, class: "btn btn-light" %>
      <%= f.submit class: "btn btn-outline-secondary" %>
    </div>

  <% end %>







<!--  <div class="col">-->
    <%#= form_for @marathon, url: admin_marathons_path do |f| %>

<!--      <div class="form-group">-->
        <%#= f.label :name, "Name:", class: "col control-label" %>
<!--        <div class="col">-->
          <%#= f.text_field :name, required: true, class: "form-control" %>
<!--        </div>-->
<!--      </div>-->

<!--      <div class="form-group">-->
        <%#= f.label :pdf_width, "PDF width:", class: "col control-label" %>
<!--        <div class="col">-->
          <%#= f.number_field :pdf_width, step: 1, placeholder: '2210', required: true, class: "form-control" %>
<!--        </div>-->
<!--      </div>-->

<!--      <div class="form-group">-->
        <%#= f.label :pdf_height, "PDF height:", class: "col control-label" %>
<!--        <div class="col">-->
          <%#= f.number_field :pdf_height, step: 1, placeholder: '1563', required: true, class: "form-control" %>
<!--        </div>-->
<!--      </div>-->

<!--      <div class="form-group">-->
        <%#= f.label :x_pos, "X-pos:", class: "col control-label" %>
<!--        <div class="col">-->
          <%#= f.number_field :x_pos, step: 1, placeholder: '400', required: true, class: "form-control" %>
<!--        </div>-->
<!--      </div>-->

<!--      <div class="form-group">-->
        <%#= f.label :y_pos, "Y-pos:", class: "col control-label" %>
<!--        <div class="col">-->
          <%#= f.number_field :y_pos, step: 1, placeholder: '-100', required: true, class: "form-control" %>
<!--        </div>-->
<!--      </div>-->

<!--      <div class="form-group">-->
        <%#= f.label :font_size, "Font size:", class: "col control-label" %>
<!--        <div class="col">-->
          <%#= f.number_field :font_size, min: 1, step: 1, placeholder: '82', required: true, class: "form-control" %>
<!--        </div>-->
<!--      </div>-->

<!--      <div class="form-group">-->
        <%#= f.label :font_color, "Font color (CMYK code):", class: "col control-label" %>
<!--        <div class="col">-->
          <%#= f.text_field :font_color, placeholder: '0,0,0,0', required: true, class: "form-control" %>
<!--        </div>-->
<!--      </div>-->

<!--      <div class="form-group">-->
        <%#= f.label :description, "Description:", class: "col control-label" %>
<!--        <div class="col">-->
          <%#= f.text_field :description, placeholder: 'Description', required: true, class: "form-control" %>
<!--        </div>-->
<!--      </div>-->

<!--      <div class="form-group">-->
        <%#= f.label :logo, "Image logo:", class: "col control-label" %>
<!--        <div class="col">-->
          <%#= f.file_field :logo, required: true, class: "form-control" %>
<!--        </div>-->
<!--      </div>-->

<!--      <div class="form-group mt-5 ml-3">-->
        <%#= link_to "back", admin_marathons_path, class: "btn btn-light" %>
        <%#= f.submit class: "btn btn-outline-secondary" %>
<!--      </div>-->
    <%# end %>
<!--  </div>-->

</div>

app/views/admin/marathons/show.html.erb
<div class="container mt-5">

  <div class="d-flex justify-content-between">
    <h1>Marathon "<%= @marathon.name %>"</h1>
    <div style="display: flex; align-items: center; justify-content: flex-start;">
      <%= link_to 'Edit', edit_admin_marathon_path(@marathon), class: "btn btn-outline-secondary btn-sm" %>
      <%= button_to 'Delete', admin_marathon_path(@marathon), class: 'btn btn-outline-danger btn-sm ml-2', method: :delete, data: { confirm: 'Are you sure you want to DELETE this Marathon?' } %>
      <%= link_to 'Add User', new_admin_user_path(marathon_id: @marathon.id), class: "btn ml-2 btn-success btn-sm" %>

    </div>
  </div>
  <hr>
  <p class="font-weight-normal"><%= @marathon.description %></p>

  <div class="row">
    <div class="col-sm-4">
      <img src="<%= @marathon.logo.url %>" alt="..." style="height: 15em; width: 15em; padding: 16px;">


      <table class="table table-borderless table-sm">
        <thead>
        <tr>
          <th scope="col" style="width: 30%;"></th>
          <th scope="col" style="width: 70%;"></th>
        </tr>
        </thead>
        <tbody>

        <tr>
          <td><span class="font-weight-lighter">Created at:</span></td>
          <td><span class="font-weight-lighter"><%= @marathon.created_at.strftime('%d.%m.%y %H:%M') %></span></td>
        </tr>

        <tr>
          <td><span class="font-weight-lighter">Updated at:</span></td>
          <td><span class="font-weight-lighter"><%= @marathon.updated_at.strftime('%d.%m.%y %H:%M') %></span></td>
        </tr>

        </tbody>
      </table>



    </div>



    <div class="col-sm-8">
      <table class="table table-borderless table-sm">
        <thead>
        <tr>
          <th scope="col" style="width: 20%;"></th>
          <th scope="col" style="width: 80%;"></th>
        </tr>
        </thead>
        <tbody>

        <tr>
          <td><span class="font-weight-lighter">Resolution:</span></td>
          <td><span class="font-weight-normal"><%= @marathon.get_resolution %></span></td>
        </tr>

        <tr>
          <td><span class="font-weight-lighter">Font color:</span></td>
          <td><span class="font-weight-normal"><%= @marathon.font_color %></span></td>
        </tr>

        <tr>
          <td><span class="font-weight-lighter">Font size:</span></td>
          <td><span class="font-weight-normal"><%= @marathon.font_size %></span></td>
        </tr>

        <tr>
          <td><span class="font-weight-lighter">X-pos:</span></td>
          <td><span class="font-weight-normal"><%= @marathon.x_pos %></span></td>
        </tr>

        <tr>
          <td><span class="font-weight-lighter">Y-pos:</span></td>
          <td><span class="font-weight-normal"><%= @marathon.y_pos %></span></td>
        </tr>


        <tr>
          <td><span class="font-weight-lighter">Users:</span></td>
          <td>

            <div class="d-flex align-items-baseline">
              <%= link_to @marathon.users.count, admin_users_path(from_marathon: @marathon.id) %>
              <% if @marathon.users.any? %>
                <%= button_to '&#10007;'.html_safe, delete_all_users_admin_marathon_path(marathon_id: @marathon.id), class: 'btn btn-outline-danger btn-sm ml-2', style: 'border: none', method: :patch, data: { confirm: 'Are you sure you want to DELETE all Users of this Marathon?' }%>
              <% end %>
            </div>

          </td>

        </tr>

        <tr>
          <td><span class="font-weight-lighter">Tables:</span></td>
          <td><span class="font-weight-normal"><%= @marathon.tables.count %></span></td>
        </tr>

        <tr>
          <td><span class="font-weight-lighter">Lectures:</span></td>
          <td><span class="font-weight-normal"><%= @marathon.lectures.count %></span></td>
        </tr>



        </tbody>
      </table>

    </div>
  </div>

  <div class="d-flex align-items-center justify-content-between mt-5">
    <h3>Tables</h3>
    <%= link_to 'Create new', new_admin_table_path(marathon_id: @marathon.id), class: "btn btn-outline-primary btn-sm" %>
  </div>

  <% if @tables.any? %>
    <table class="table table-hover mt-3">
      <thead>
      <tr>
        <th scope="col" style="width: 10%; text-align: center">#</th>
<!--        <th scope="col" style="width: 20%;">Marathon</th>-->
        <th scope="col" style="width: 25%;">Name</th>
        <th scope="col" style="width: 45%;">Description</th>
        <th scope="col" style="width: 10%; text-align: center">State</th>
        <th scope="col" style="width: 10%; text-align: center"></th>
      </tr>
      </thead>
      <tbody>

      <% @tables.each_with_index { |table, index|  %>
        <% case table.state %>
        <% when 'new' %>
          <% class_name = 'primary' %>
        <% when 'error' %>
          <% class_name = 'danger' %>
        <% when 'processing' %>
          <% class_name = 'warning' %>
        <% when 'done' %>
          <% class_name = 'success' %>
        <% end %>
        <tr>
          <th scope="row" style="text-align: center"><%= index + 1 %></th>
<!--          <td><%#= table.marathon.name %></td>-->
          <td><%= table.name %></td>
          <td><%= table.description %></td>
          <td style="text-align: center"><span class="badge badge-<%= class_name %>"><%= table.state %></span></td>
          <td style="text-align: center"><%= link_to "Show", admin_table_path(table), class: "btn btn-outline-secondary btn-sm" %></td>
        </tr>
      <% } %>
      </tbody>
    </table>

  <% end %>




  <hr class="mt-5">

  <div class="d-flex align-items-center justify-content-between mt-5">
    <h3>Lectures</h3>
    <%= link_to 'Create new', new_admin_lecture_path(marathon_id: @marathon.id), class: "btn btn-outline-primary btn-sm" %>
  </div>

  <% if @lectures.any? %>
    <table class="table table-hover mt-3">
      <thead>
      <tr>
        <th scope="col" style="width: 10%; text-align: center">#</th>
        <th scope="col" style="width: 25%;">Name</th>
        <th scope="col" style="width: 15%;">Speaker</th>
<!--        <th scope="col" style="width: 30%;">Description</th>-->
        <th scope="col" style="width: 15%; text-align: center">Date</th>
        <th scope="col" style="width: 25%; text-align: center">Certificate</th>
        <th scope="col" style="width: 10%; text-align: center">Resolution</th>
        <th scope="col" style="width: 10%; text-align: center"></th>
      </tr>
      </thead>
      <tbody>

      <% @lectures.each_with_index { |lecture, index|  %>
        <% lecture.get_resolution == @marathon.get_resolution ? class_name = 'success' : class_name = 'danger' %>
        <tr>
          <th scope="row" style="text-align: center"><%= index + 1 %></th>
          <td><%= lecture.name %></td>
          <td><%= lecture.speaker %></td>
<!--          <td><%#= lecture.description %></td>-->
          <td style="text-align: center"><%= lecture.date %></td>
          <td style="text-align: center"><%= image_tag lecture.certificate.url(:thumb) %></td>

          <td style="text-align: center"><span class="badge badge-<%= class_name %>"><%= lecture.get_resolution %></span></td>

<!--          <td style="color: green"><%#= lecture.get_resolution %></td>-->
          <td><%= link_to "Show", admin_lecture_path(lecture), class: "btn btn-outline-secondary btn-sm" %></td>
        </tr>
      <% } %>
      </tbody>
    </table>

  <% end %>




  <hr class="mt-5">

  <%= link_to "All marathons", admin_marathons_path(), class: "btn btn-outline-secondary btn-sm", style: "margin-bottom: 72px;" %>

</div>