config/routes.rb
Rails.application.routes.draw do
  #devise_for :admins
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_scope :admin do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_admin_registration" # custom path to sign_up/registration
  end

  devise_for :admins, :skip => [:registrations]
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
  end

  root to: "welcome#index"
  get 'result', to: 'welcome#result'
  get 'marathons', to: 'welcome#marathons'
  get 'certificates', to: 'welcome#certificates'
  get 'download_pdf', to: "welcome#download_pdf"
  get 'download_zip', to: "welcome#download_zip"
  get 'zip_zip', to: "welcome#zip_zip"

  #resources :users, only: [:index, :show, :edit], param: :email, :constraints => { :email => /.*/ } do
  #resources :users, param: :email, :constraints => { :email => /.*/ } do
  #  get 'download_pdf', to: "users#download_pdf"
  #  get 'download_zip', to: "users#download_zip"
  #end

  #resources :certificates
  #resources :rus_templates
  #resources :eng_templates


  #get 'download_pdf', to: "users#download_pdf"

  namespace :admin do
    root 'admin#dashboard'
    resources :users

    resources :marathons do
      member do
        patch 'delete_all_users', to: 'marathons#delete_all_users'
      end
    end

    resources :lectures
    resources :certificates
    resources :rus_templates
    resources :eng_templates
    resources :tables do
      member do
        patch 'create_users', to: 'tables#create_users'
        patch 'renew', to: 'tables#renew'
      end
    end
    get 'download_one_pdf', to: "users#download_one_pdf"
    get 'download_all_pdfs', to: "users#download_all_pdfs"
  end

end

app/models/user.rb
# frozen_string_literal: true
class User < ApplicationRecord
  extend Enumerize

  belongs_to :table, optional: true
  belongs_to :marathon

  validates :firstname, presence: true
  #validates :lastname, presence: true
  # validates :language, presence: true
  validates :email, uniqueness: { case_sensitive: false, scope: :marathon }


  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create

  after_save :name_template_full, if: -> { saved_change_to_firstname? || saved_change_to_lastname? }

  has_attached_file :text
  do_not_validate_attachment_file_type :text

  scope :already_done, -> { where(state: 'done') }
  scope :of_one_marathon, ->(marathon_id) { where(marathon_id: marathon_id) }

  enumerize :state, in: ['done', 'wait'], default: 'wait'

  def name_to_paste
    firstname.upcase + (" #{lastname.upcase}" if lastname).to_s
  end


  def combine_pdf_cert(certificate)
    language == 'rus' ? using_template = certificate.rus_template : using_template = certificate.eng_template
    fonts = CombinePDF.new(Rails.root.join('public','font-montserrat.pdf')).fonts(true)
    CombinePDF.register_font_from_pdf_object :montserrat, fonts[0]
    template_pdf = CombinePDF.load(using_template.pdf_file.path)
    #template_pdf.pages[0].textbox("#{firstname} #{lastname}", { font: :montserrat,
    template_pdf.pages[0].textbox(name_to_paste, { font: :montserrat,
                                                                font_color: using_template.font_color.split(',').map(&:to_i),
                                                                font_size: using_template.font_size,
                                                                x: using_template.xpos,
                                                                y: using_template.ypos })
    template_pdf.to_pdf
  end



  #def combine_pdf_cert(type)
  #  type == 'main' ? position = {:x => 0, :y => -420} : position = {:x => 680, :y => 190}
  #
  #  fonts = CombinePDF.new(Rails.root.join('public','font-montserrat.pdf')).fonts(true)
  #  CombinePDF.register_font_from_pdf_object :montserrat, fonts[0]
  #  template_pdf = CombinePDF.load(Rails.root.join('public',"#{type}.pdf"))
  #  template_pdf.pages[0].textbox("#{firstname} #{lastname}", { font: :montserrat, font_color: [255,250,250], font_size: 82, x: position[:x], y: position[:y]})

                  #template_pdf.save Rails.root.join('public','main-new.pdf')

  #  template_pdf.to_pdf
  #end


  def generate_cert_with_prawn(certificate)
    #hhh = 800
    #left = 914
    #length = 948

    language == 'rus' ? using_template = certificate.rus_template : using_template = certificate.eng_template
    name_width > 180 ? width_koeff = 180.0/name_width : width_koeff = 1.0
    color = using_template.font_color.split(',').map(&:to_i)
    #start_pos = using_template.xpos - ((name_width * using_template.font_size * 1.71) / 2)
    start_pos = using_template.xpos - ((name_width * using_template.font_size * width_koeff * 1.76 / 15) / 2)

    prawn_text_pdf = Prawn::Document.new :page_size => [using_template.pdf_height, using_template.pdf_width], :margin => 0 do |pdf|
      pdf.fill_color color[0], color[1], color[2], color[3]
      pdf.font Rails.root.join('public','Montserrat-Medium.ttf')
      pdf.draw_text name_to_paste, :at => [start_pos, using_template.ypos], :size => using_template.font_size * width_koeff * 0.7 * 2

      #pdf.text_box name_to_paste,
      #             size: using_template.font_size * 0.7 * 2,
      #             at: [left, hhh + using_template.font_size * 0.8 * 2],
      #             align: :center,
      #             valign: :top,
      #             width: length

    end

    pdf_data = prawn_text_pdf.render
    combine_text_pdf = CombinePDF.parse(pdf_data).pages[0]

    cert_pdf = CombinePDF.load using_template.pdf_file.path
    cert_pdf.pages[0] << combine_text_pdf
    cert_pdf.to_pdf

  end

  def generate_all_certs
    name_width > 180 ? width_koeff = 180.0/name_width : width_koeff = 1.0

    main_cert = Certificate.where(name: 'main').first
    speaker_cert = Certificate.where.not(name: 'main').first

    main_template = main_cert.rus_template
    speaker_template = speaker_cert.rus_template

    main_start_pos = main_template.xpos - ((name_width * main_template.font_size * width_koeff * 1.76 / 15) / 2)
    main_color = main_template.font_color.split(',').map(&:to_i)
    main_text_pdf = Prawn::Document.new :page_size => [main_template.pdf_height,
                                                       main_template.pdf_width],
                                        :margin => 0 do |pdf|
      pdf.fill_color main_color[0], main_color[1], main_color[2], main_color[3]
      pdf.font Rails.root.join('public','Montserrat-Medium.ttf')
      pdf.draw_text name_to_paste, :at => [main_start_pos, main_template.ypos], :size => main_template.font_size * width_koeff * 0.7 * 2
    end
    main_text_pdf = main_text_pdf.render
    combine_main = CombinePDF.parse(main_text_pdf).pages[0]
    #main_text_pdf = nil

    speaker_start_pos = speaker_template.xpos - ((name_width * speaker_template.font_size * width_koeff * 1.76 / 15) / 2)
    speaker_color = speaker_template.font_color.split(',').map(&:to_i)
    speaker_text_pdf = Prawn::Document.new :page_size => [speaker_template.pdf_height,
                                                          speaker_template.pdf_width],
                                        :margin => 0 do |pdf|
      pdf.fill_color speaker_color[0], speaker_color[1], speaker_color[2], speaker_color[3]
      pdf.font Rails.root.join('public','Montserrat-Medium.ttf')
      pdf.draw_text name_to_paste, :at => [speaker_start_pos, speaker_template.ypos], :size => speaker_template.font_size * width_koeff * 0.7 * 2
    end
    speaker_text_pdf = speaker_text_pdf.render
    combine_speaker = CombinePDF.parse(speaker_text_pdf).pages[0]
    #speaker_text_pdf = nil

    case language
    when 'rus'
      all_templates = RusTemplate.all.includes(:certificate)
    when 'eng'
      all_templates = EngTemplate.all.includes(:certificate)
    end

    #filename = "#{email}_all_certs.zip"
    #zip_file = Tempfile.new(filename)
    Zip::OutputStream.write_buffer do |zip|
      all_templates.each do |type|
        cert = Tempfile.new("#{type.certificate.name}-#{email}.pdf")
        cert.binmode
        type.certificate.name == 'main' ? combine_text_pdf = combine_main : combine_text_pdf = combine_speaker
        cert_pdf = CombinePDF.load type.pdf_file.path
        cert_pdf.pages[0] << combine_text_pdf
        one_cert = cert_pdf.to_pdf
        cert.write(one_cert)
        zip.put_next_entry("#{type.certificate.name}-#{email}.pdf")
        zip.write IO.read(cert.path)
        cert.close
        cert.unlink
      end
    end
    # result = File.read(zip_file.path)
    # zip_file.close
    # zip_file.unlink
    # result
  end

  def generate_cert_by_template(template)
    name_width > 180 ? width_koeff = 180.0/name_width : width_koeff = 1.0
    color = template.font_color.split(',').map(&:to_i)
    start_pos = template.xpos - ((name_width * template.font_size * width_koeff * 1.76 / 15) / 2)
    prawn_text_pdf = Prawn::Document.new :page_size => [template.pdf_height, template.pdf_width], :margin => 0 do |pdf|
      pdf.fill_color color[0], color[1], color[2], color[3]
      pdf.font Rails.root.join('public','Montserrat-Medium.ttf')
      pdf.draw_text name_to_paste, :at => [start_pos, template.ypos], :size => template.font_size * width_koeff * 0.7 * 2
    end
    pdf_data = prawn_text_pdf.render
    combine_text_pdf = CombinePDF.parse(pdf_data).pages[0]
    cert_pdf = CombinePDF.load template.pdf_file.path
    cert_pdf.pages[0] << combine_text_pdf
    cert_pdf.to_pdf
  end

  ###################

  def generate_one_cert(lecture)
    cert_pdf = CombinePDF.load lecture.certificate.path
    cert_pdf.pages[0] << CombinePDF.load(text.path).pages[0]
    cert_pdf.to_pdf
  end

  def generate_all_certs_new
    Zip::OutputStream.write_buffer do |zip|
      marathon.lectures.each do |type|
        cert = Tempfile.new("#{type.file_name}-#{email}.pdf")
        cert.binmode
        combine_text_pdf = CombinePDF.load(text.path).pages[0]
        cert_pdf = CombinePDF.load type.certificate.path
        cert_pdf.pages[0] << combine_text_pdf
        one_cert = cert_pdf.to_pdf
        cert.write(one_cert)
        zip.put_next_entry("#{type.file_name}-#{email}.pdf")
        zip.write IO.read(cert.path)
        cert.close
        cert.unlink
      end
    end
  end

  def generate_name_pdf
    # name_width > 180 ? width_koeff = 180.0/name_width : width_koeff = 1.0
    color = marathon.font_color.split(',').map(&:to_i)
    # start_pos = marathon.x_pos - ((name_width * marathon.font_size * width_koeff * 1.76 / 15) / 2)
    start_pos = marathon.x_pos - ((name_width * marathon.font_size * 1.76 / 15) / 2)
    prawn_text_pdf = Prawn::Document.new :page_size => [marathon.pdf_width, marathon.pdf_height], :margin => 0 do |pdf|
      pdf.fill_color color[0], color[1], color[2], color[3]
      pdf.font Rails.root.join('public', 'Montserrat-Medium.ttf')
      # pdf.draw_text name_to_paste, :at => [start_pos, marathon.y_pos], :size => marathon.font_size * width_koeff * 0.7 * 2
      pdf.draw_text name_to_paste, :at => [start_pos, marathon.y_pos], :size => marathon.font_size * 0.7 * 2
    end
    update!(
      text: StringIO.new(prawn_text_pdf.render),
      text_file_name: "Clear_name_text_#{DateTime.now.strftime("%Y_%m_%d_%H_%M_%S")}.pdf",
      state: 'wait'
    )
  end

  private

  # def set_name_width
  #   label = Magick::Draw.new
  #   label.font = Rails.root.join('public','Montserrat-Medium.ttf').to_s
  #   width = label.get_type_metrics(name_to_paste).width
  #   self.name_width = width
  #   save
  # end

  def name_template_full
    label = Magick::Draw.new
    label.font = Rails.root.join('public', 'Montserrat-Medium.ttf').to_s
    width = label.get_type_metrics(name_to_paste).width

app/controllers/admin/users_controller.rb
#require('zip')
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!, except: [:download_one_pdf, :download_all_pdfs]

  def index
    @marathons = Marathon.all

    if params[:from_marathon]
      @q = User.includes(:marathon).of_one_marathon(params[:from_marathon]).ransack(params[:q])
    else
      @q = User.includes(:marathon).ransack(params[:q])
    end

    # @q = User.ransack(params[:q])
    @users = @q.result.page(params[:page]).per(100)
  end

  def new
    @marathons = Marathon.all
    @user = User.new
  end

  def create
    @marathons = Marathon.all
    @user = User.create(user_params)

    if @user.save
      flash[:success] = "New User successfully created!"
      redirect_to admin_users_path
    else
      flash.now[:danger] = "Ooops! Something went wrong! #{@user.errors.full_messages.to_sentence}"
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    @marathons = Marathon.all
  end

  def update
    @user = User.find(params[:id])
    @marathons = Marathon.all
    if @user.update(user_params)
      flash[:success] = "User updated!"
      redirect_to admin_user_path(@user)
    else
      flash.now[:danger] = "Ooops! Something went wrong! #{@user.errors.full_messages.to_sentence}"
      render action: :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:success] = "User was successfully deleted!"
      redirect_to admin_users_path
    else
      flash[:danger] = "Ooops! Something went wrong! #{@user.errors.full_messages.to_sentence}"
      render action: :show
    end
  end

  def download_one_pdf
    @user = User.find(params[:id])
    @lecture = Lecture.find(params[:lecture_id])
    send_data(@user.generate_one_cert(@lecture), filename: "#{@lecture.file_name}_cert.pdf", type: 'application/pdf')
  end

  def download_all_pdfs
    @user = User.find(params[:id])
    filename = 'all_certs_archive.zip'
    certs_files = @user.generate_all_certs_new
    certs_files.rewind
    send_data(certs_files.read, type: 'application/zip', disposition: 'attachment', filename: filename)
    @user.update(state: 'done')
  end

  private
  def user_params
    params.require(:user).permit(:firstname, :lastname, :email, :language, :marathon_id)
  end

end

app/views/admin/users/edit.html.erb
<div class="container mt-5">

  <h1>Edit User #<%= @user.id %></h1>

  <h6 class="mb-5">All fields are required (except Lastname)</h6>

  <%= form_for @user, url: admin_user_path do |f| %>

    <div class="form-group">
      <%= f.label :marathon_id, "Marathon:", class: "col control-label" %>
      <div class="col">
        <%= f.select :marathon_id, options_from_collection_for_select(@marathons, "id", "name", params[:marathon_id]), { prompt: '-- Select One --'}, {required: true, class: "form-control", disabled: true} %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :firstname, "Firstname:", class: "col control-label" %>
      <div class="col">
        <%= f.text_field :firstname, required: true, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :lastname, "Lastname:", class: "col control-label" %>
      <div class="col">
        <%= f.text_field :lastname, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :email, "Email:", class: "col control-label" %>
      <div class="col">
        <%= f.text_field :email, required: true, class: "form-control" %>
      </div>
    </div>

<!--    <div class="form-group">-->
      <%#= f.label :language, "Language:", class: "col control-label" %>
<!--      <div class="col">-->
        <%#= f.select :language, options_for_select(%w(rus eng)), { prompt: '-- Select One --'}, {required: true, class: "form-control"} %>
        <%#= f.select :language, %w(rus eng), { required: true }, { class: "form-control" } %>
<!--      </div>-->
<!--    </div>-->

    <div class="form-group mt-5 ml-3">
      <%= link_to "back", admin_users_path, class: "btn btn-light" %>
      <%= f.submit class: "btn btn-outline-secondary" %>
    </div>

  <% end %>

</div>

app/views/admin/users/index.html.erb
<div class="container mt-5">
  <div class="d-flex align-items-center justify-content-between">
    <h1>All Users</h1>
    <%= link_to 'Create new', new_admin_user_path(), class: "btn btn-outline-primary btn-sm" %>
  </div>

  <h6 class="text-muted font-weight-light">Created participants in the system for <span style="font-weight: bold">all</span> marathons <span class="badge badge-light"><%= User.count %></span></h6>

  <form class="mt-5" style="width: 100%; border: 1px solid #ced4da; border-radius: .25rem; padding-bottom: 16px; padding-top: 16px">
    <div class="search-wrap">

      <%= search_form_for @q, url: admin_users_path do |f| %>

        <div style="width: 5%; padding: 5px;">
        </div>

        <div style="width: 20%; padding: 5px;">
          <%= f.select :marathon_id_eq, options_from_collection_for_select(@marathons, "id", "name", params.dig('q', 'marathon_id_eq') || params[:from_marathon]), { :include_blank => true }, class: "form-control" %>
        </div>

        <div style="width: 15%; padding: 5px;">
          <%= f.search_field :firstname_cont, class: "form-control", placeholder: "contains" %>
        </div>

        <div style="width: 15%; padding: 5px;">
          <%= f.search_field :lastname_cont, class: "form-control", placeholder: "contains" %>
        </div>

        <div style="width: 20%; padding: 5px;">
          <%= f.search_field :email_cont, class: "form-control", placeholder: "contains" %>
        </div>

        <div style="width: 10%; padding: 5px;">
          <%= f.select :state_eq, options_for_select(['done', 'wait'], params.dig('q', 'state_eq')), { :include_blank => true }, { class: "form-control", placeholder: "equals" } %>
        </div>

        <div style="width: 15%; padding: 5px; display: flex; justify-content: center;">
          <div class="btn-group" role="group" aria-label="Basic example">
            <%= f.submit :Search, type: "submit", class: "btn btn-sm btn-outline-success" %>
            <%= link_to '&times;'.html_safe, request.path, class: "btn btn-sm btn-success" %>
          </div>
        </div>

      <% end %>

    </div>
  </form>

  <div class="row mt-5">
    <div class="col-12">

      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col" style="text-align: center; width: 5%">#</th>
            <th scope="col" style="width: 20%">Marathon</th>
            <th scope="col" style="width: 15%">Firstname</th>
            <th scope="col" style="width: 15%">Lastname</th>
            <th scope="col" style="width: 20%">Email</th>
            <th scope="col" style="text-align: center; width: 10%">State</th>
            <th scope="col" style="text-align: center; width: 15%"></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each_with_index { |user, index|  %>
            <tr>
              <th style="text-align: center; width: 5%" scope="row"><%= index + 1 %></th>
              <td style="width: 20%"><%= user.marathon.name %></td>
              <td style="width: 15%"><%= user.firstname %></td>
              <td style="width: 15%"><%= user.lastname %></td>
              <td style="width: 20%"><%= user.email %></td>
              <td style="text-align: center; width: 10%">
                <% if user.state == 'done' %>
                  <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="green" class="bi bi-check-circle-fill mr-2" viewBox="0 0 16 16">
                    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
                  </svg>
                <% end %>
              </td>
              <td style="text-align: center; width: 15%"><%= link_to 'show', admin_user_path(user), class: "btn btn-outline-secondary btn-sm" %></td>
            </tr>
          <% } %>
        </tbody>

      </table>

    </div>
  </div>

  <div class="d-flex align-items-center justify-content-center mt-3" style="padding-bottom: 44px">
    <%= paginate @users %>
  </div>

<!--  <div class="col" style="max-width: 30%; position: relative;">-->
<!--    <div class="search-form" style="max-width: 30%;">-->
<!--      <form>-->
<!--        <h4 class="d-flex justify-content-center mt-3 mb-3">Search users</h4>-->
<!--        <div>-->
          <%#= search_form_for @q, url: admin_users_path do |f| %>

<!--              <div class="form-group">-->
                <%#= f.label "Firstname:", class: "col-md-4 control-label" %>
<!--                <div class="col-auto">-->
                  <%#= f.search_field :firstname_cont, class: "form-control", placeholder: "contains" %>
<!--                </div>-->
<!--              </div>-->

<!--              <div class="form-group">-->
                <%#= f.label "Lastname:", class: "col-md-4 control-label" %>
<!--                <div class="col-auto">-->
                  <%#= f.search_field :lastname_cont, class: "form-control", placeholder: "contains" %>
<!--                </div>-->
<!--              </div>-->

<!--            <div class="form-group">-->
              <%#= f.label "Email:", class: "col-md-4 control-label" %>
<!--              <div class="col-auto">-->
                <%#= f.search_field :email_cont, class: "form-control", placeholder: "contains" %>
<!--              </div>-->
<!--            </div>-->

<!--            <div class="form-group">-->
              <%#= f.label "State:", class: "col-md-4 control-label" %>
<!--              <div class="col-auto">-->
                <%#= f.select :state_eq, options_for_select(['done', 'wait'], params.dig('q', 'state_eq')), { :include_blank => true }, { class: "form-control", placeholder: "equals" } %>
<!--              </div>-->
<!--            </div>-->

<!--            <div class="form-group">-->
              <%#= f.label "Marathon:", class: "col-md-4 control-label" %>
<!--              <div class="col-auto">-->
                <%#= f.select :language_eq, options_for_select(%w(rus eng)), { prompt: '-- Select One --' }, class: "form-control" %>
                <%#= f.select :marathon_id_eq, options_from_collection_for_select(@marathons, "id", "name", params.dig('q', 'marathon_id_eq') || params[:from_marathon]), { :include_blank => true }, class: "form-control" %>
<!--              </div>-->
<!--            </div>-->

<!--            <div class="col-auto d-flex justify-content-end mt-3 mb-3">-->
              <%#= f.submit :Search, type: "submit", class: "btn btn-outline-success" %>
              <%#= link_to '&times;'.html_safe, request.path, class: "btn btn-light ml-3" %>
<!--            </div>-->
          <%# end %>
<!--        </div>-->
<!--      </form>-->
<!--    </div>-->
<!--  </div>-->

</div>

app/views/admin/users/show.html.erb
<div class="container mt-5">

  <div class="d-flex justify-content-between">
    <div class="d-flex align-items-baseline">
      <% if @user.state == 'done' %>
        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="green" class="bi bi-check-circle-fill mr-2" viewBox="0 0 16 16">
          <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
        </svg>
      <% end %>
      <h1>
      User #<%= @user.id %>
    </h1>
    </div>

    <div style="display: flex; align-items: center; justify-content: flex-start;">
      <%= link_to 'Edit', edit_admin_user_path(@user), class: "btn btn-outline-secondary btn-sm" %>
      <%= button_to 'Delete', admin_user_path(@user), class: 'btn btn-outline-danger btn-sm ml-2', method: :delete, data: { confirm: 'Are you sure you want to DELETE this User?' } %>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-sm-9">
      <table class="table table-borderless table-sm">
        <thead>
        <tr>
          <th scope="col" style="width: 30%;"></th>
          <th scope="col" style="width: 70%;"></th>
        </tr>
        </thead>
        <tbody>

        <tr>
          <td><span class="font-weight-lighter">Marathon:</span></td>
          <td><span class="font-weight-normal"><%= link_to @user.marathon.name, admin_marathon_path(@user.marathon) %></span></td>

        </tr>

        <tr>
          <td><span class="font-weight-lighter">Email:</span></td>
          <td><span class="font-weight-normal"><%= @user.email %></span></td>
        </tr>

        <tr>
          <td><span class="font-weight-lighter">Firstname:</span></td>
          <td><span class="font-weight-normal"><%= @user.firstname %></span></td>
        </tr>

        <tr>
          <td><span class="font-weight-lighter">Lastname:</span></td>
          <td><span class="font-weight-normal"><%= @user.lastname %></span></td>
        </tr>

<!--        <tr>-->
<!--          <td><span class="font-weight-lighter">Language:</span></td>-->
<!--          <td><span class="font-weight-normal"><%#= @user.language %></span></td>-->
<!--        </tr>-->

        <tr>
          <td><span class="font-weight-lighter">Created:</span></td>
          <td>
            <% if @user.table %>
              <span class="font-weight-normal">from table <a href="<%= admin_table_url(@user.table) %>"><%= @user.table.name %></a></span></td>
            <% else %>
              <span class="font-weight-normal">manually</span>
            <% end %>
          </td>
        </tr>

        <tr>
          <td><span class="font-weight-lighter">Template file with name:</span></td>
          <td><span class="font-weight-normal"><%= link_to "open", @user.text.url(:original, false), target: :_blank %></span></td>
        </tr>

        <tr>
          <td><span class="font-weight-lighter">Created at:</span></td>
          <td><span class="font-weight-lighter"><%= @user.created_at.strftime('%d.%m.%y %H:%M') %></span></td>
        </tr>

        <tr>
          <td><span class="font-weight-lighter">Updated at:</span></td>
          <td><span class="font-weight-lighter"><%= @user.updated_at.strftime('%d.%m.%y %H:%M') %></span></td>
        </tr>

        </tbody>
      </table>
    </div>
  </div>

  <hr>

  <div class="d-flex justify-content-between">
    <%= link_to "All users", admin_users_path(), class: "btn btn-outline-secondary btn-sm" %>
    <div style="display: flex; align-items: center; justify-content: flex-start;">
      <% if @user.marathon.lectures.any? %>
        <a class="btn btn-success btn-sm" href="<%= admin_download_one_pdf_path(id: @user.id, lecture_id: @user.marathon.lectures.sample.id) %>" target="_blank">
          Download ONE
        </a>
        <a class="btn btn-success btn-sm ml-2" href="<%= admin_download_all_pdfs_path(id: @user.id, admin: true) %>" target="_blank">
          Download ZIP
        </a>
      <% end %>
    </div>
  </div>






</div>