config/routes.rb
Rails.application.routes.draw do
  #devise_for :admins
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_scope :admin do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_admin_registration" # custom path to sign_up/registration
  end

  devise_for :admins, :skip => [:registrations]
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
  end

  root to: "welcome#index"
  get 'result', to: 'welcome#result'
  get 'marathons', to: 'welcome#marathons'
  get 'certificates', to: 'welcome#certificates'
  get 'download_pdf', to: "welcome#download_pdf"
  get 'download_zip', to: "welcome#download_zip"
  get 'zip_zip', to: "welcome#zip_zip"

  #resources :users, only: [:index, :show, :edit], param: :email, :constraints => { :email => /.*/ } do
  #resources :users, param: :email, :constraints => { :email => /.*/ } do
  #  get 'download_pdf', to: "users#download_pdf"
  #  get 'download_zip', to: "users#download_zip"
  #end

  #resources :certificates
  #resources :rus_templates
  #resources :eng_templates


  #get 'download_pdf', to: "users#download_pdf"

  namespace :admin do
    root 'admin#dashboard'
    resources :users

    resources :marathons do
      member do
        patch 'delete_all_users', to: 'marathons#delete_all_users'
      end
    end

    resources :lectures
    resources :certificates
    resources :rus_templates
    resources :eng_templates
    resources :tables do
      member do
        patch 'create_users', to: 'tables#create_users'
        patch 'renew', to: 'tables#renew'
      end
    end
    get 'download_one_pdf', to: "users#download_one_pdf"
    get 'download_all_pdfs', to: "users#download_all_pdfs"
  end

end

app/models/certificate.rb
class Certificate < ApplicationRecord

  validates :name, presence: true
  validates :speaker, presence: true
  validates :description, presence: true
  validates :date, presence: true

  has_one :rus_template, dependent: :destroy
  accepts_nested_attributes_for :rus_template, reject_if: :all_blank
  validates_associated :rus_template

  has_one :eng_template, dependent: :destroy
  accepts_nested_attributes_for :eng_template, reject_if: :all_blank
  validates_associated :eng_template

  scope :rus, -> { joins(:rus_template) }
  scope :eng, -> { joins(:eng_template) }
  scope :no_templates, -> { includes(:rus_template,:eng_template).where(rus_templates: { id: nil }, eng_templates: { id: nil }) }

  #validates :language, presence: true, inclusion: %w(rus eng)
  #validates :xpos, presence: true, numericality: { only_integer: true }
  #validates :ypos, presence: true, numericality: { only_integer: true }
  #
  #has_attached_file :template, styles: { :thumb => ["200x200>", :png], :medium => ["500x500>", :png] }
  #validates_attachment :template, presence: true,
  #                     content_type: { content_type: ['application/pdf'] },
  #                     message: ' Only PDF files are allowed.'


  def self.scope_by_language(language)
    joins(:"#{language}_template").order(date: :desc)
  end


end

app/controllers/admin/certificates_controller.rb
class Admin::CertificatesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @certificates = Certificate.all.order(date: :desc)
  end

  def show
    @certificate = Certificate.find(params[:id])
    @rus_template = @certificate.rus_template
    @eng_template = @certificate.eng_template

  end

  def new
    @certificate = Certificate.new
    @certificate.build_rus_template
    @certificate.build_eng_template
  end

  def create
    @certificate = Certificate.create(certificate_params)

    if @certificate.save
      flash[:success] = "New Certificate successfully created!"
      redirect_to admin_certificate_path(@certificate)
    else
      flash[:danger] = "Ooops! Something went wrong! #{@certificate.errors.full_messages.to_sentence}"
      render :new
    end
  end

  def destroy
    @certificate = Certificate.find(params[:id])
    if @certificate.destroy
      flash[:success] = "Certificate was successfully deleted!"
      redirect_to admin_certificates_path
    else
      flash[:danger] = "Ooops! Something went wrong! #{@certificate.errors.full_messages.to_sentence}"
      render action: :show
    end
  end

  def edit
    @certificate = Certificate.find(params[:id])
  end

  def update
    @certificate = Certificate.find(params[:id])
    if @certificate.update(certificate_params)
      flash[:success] = "Certificate updated!"
      redirect_to admin_certificate_path(@certificate)
    else
      flash.now[:danger] = "Ooops! Something went wrong! #{@certificate.errors.full_messages.to_sentence}"
      render action: :edit
    end
  end



  private

# Use strong_parameters for attribute whitelisting
# Be sure to update your create() and update() controller methods.

  def certificate_params
    #params.require(:certificate).permit(:name, :speaker, :description, :date, :language, :xpos, :ypos, :template)
    params.require(:certificate).permit(:name, :speaker, :description, :date, :speaker_eng, :description_eng,
                                        rus_template_attributes: [:xpos, :ypos, :font_size, :font_color, :pdf_file],
                                        eng_template_attributes: [:xpos, :ypos, :font_size, :font_color, :pdf_file])
  end

end

app/views/admin/certificates/edit.html.erb
<div class="container mt-5">
  <h1>Edit Certificate #<%= @certificate.id %></h1>
  <h6 class="mb-5">All fields are required</h6>
  <%= form_for @certificate, url: admin_certificate_path, html: { multipart: true } do |form| %>

    <div class="form-group">
      <%= form.label :speaker, "Speaker:", class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= form.text_field :speaker, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :speaker_eng, "Speaker (eng):", class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= form.text_field :speaker_eng, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :description, "Description:", class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= form.text_area :description, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :description_eng, "Description (eng):", class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= form.text_area :description_eng, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :date, "Date:", class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= form.date_field :date, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :name, "Filename:", class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= form.text_field :name, class: "form-control" %>
      </div>
    </div>

    <div class="form-group mt-5 ml-3">
      <%= link_to "back", admin_certificate_path(@certificate), class: "btn btn-light" %>
      <%= form.submit class: "btn btn-outline-secondary" %>
    </div>

  <% end %>

</div>

app/views/admin/certificates/index.html.erb
<div class="container mt-5">
  <div class="d-flex align-items-center justify-content-between">
    <h1>Certificates</h1>
    <%= link_to 'Create new', new_admin_certificate_path(), class: "btn btn-outline-primary btn-sm" %>
  </div>

  <h6 class="text-muted font-weight-light">for English speaking participants <span class="badge badge-light"><%= Certificate.scope_by_language('eng').count %></span></h6>
  <h6 class="text-muted font-weight-light">for Russian speaking participants <span class="badge badge-light"><%= Certificate.scope_by_language('rus').count %></span></h6>

  <table class="table table-hover mt-5">
    <thead>
    <tr>
      <th scope="col" style="width: 5%; text-align: center">#</th>
      <th scope="col" style="width: 20%;">Speaker</th>
      <th scope="col" style="width: 45%;">Description</th>
      <th scope="col" style="width: 10%; text-align: center">Date</th>
      <th scope="col" style="width: 5%;">Rus</th>
      <th scope="col" style="width: 5%;">Eng</th>
      <th scope="col" style="width: 10%; text-align: center"></th>
    </tr>
    </thead>
    <tbody>

    <% @certificates.each_with_index { |cert, index|  %>
      <tr>
        <% speaker_class = 'text-danger' if (cert.speaker_eng == nil || cert.speaker_eng == '') && cert.eng_template.present? %>
        <% description_class = 'text-danger' if (cert.description_eng == nil || cert.description_eng == '') && cert.eng_template.present? %>

        <th style="text-align: center" scope="row"><%= index + 1 %></th>
        <td class=<%= speaker_class %>>
          <%= cert.speaker %>
        </td>
        <td class=<%= description_class %>>
          <%= cert.description %>
        </td>
        <td style="text-align: center"><%= cert.date.strftime('%d.%m.%y') %></td>

        <td style="text-align: center">
          <% if cert.rus_template %>
            <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-journal-check" fill="green" xmlns="http://www.w3.org/2000/svg">
              <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2z"/>
              <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z"/>
              <path fill-rule="evenodd" d="M10.854 6.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 8.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
            </svg>
          <% else %>
            <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-journal-x" fill="red" xmlns="http://www.w3.org/2000/svg">
              <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2z"/>
              <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z"/>
              <path fill-rule="evenodd" d="M6.146 6.146a.5.5 0 0 1 .708 0L8 7.293l1.146-1.147a.5.5 0 1 1 .708.708L8.707 8l1.147 1.146a.5.5 0 0 1-.708.708L8 8.707 6.854 9.854a.5.5 0 0 1-.708-.708L7.293 8 6.146 6.854a.5.5 0 0 1 0-.708z"/>
            </svg>
          <% end %>
        </td>

        <td style="text-align: center">
          <% if cert.eng_template %>
            <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-journal-check" fill="green" xmlns="http://www.w3.org/2000/svg">
              <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2z"/>
              <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z"/>
              <path fill-rule="evenodd" d="M10.854 6.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 8.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
            </svg>
          <% else %>
            <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-journal-x" fill="red" xmlns="http://www.w3.org/2000/svg">
              <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2z"/>
              <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z"/>
              <path fill-rule="evenodd" d="M6.146 6.146a.5.5 0 0 1 .708 0L8 7.293l1.146-1.147a.5.5 0 1 1 .708.708L8.707 8l1.147 1.146a.5.5 0 0 1-.708.708L8 8.707 6.854 9.854a.5.5 0 0 1-.708-.708L7.293 8 6.146 6.854a.5.5 0 0 1 0-.708z"/>
            </svg>
          <% end %>
        </td>

        <td style="text-align: center"><%= link_to 'show', admin_certificate_path(cert), class: "btn btn-outline-secondary btn-sm" %></td>

      </tr>
    <% } %>
    </tbody>
  </table>


</div>

app/views/admin/certificates/show.html.erb
<div class="container mt-5">

  <div class="d-flex justify-content-between">
    <h1>Certificate #<%= @certificate.id %></h1>
    <div style="display: flex; align-items: center; justify-content: flex-start;">
      <%= link_to 'Edit', edit_admin_certificate_path(@certificate), class: "btn btn-outline-secondary btn-sm" %>
      <%= button_to 'Delete', admin_certificate_path(@certificate), class: 'btn btn-outline-danger btn-sm ml-2', method: :delete, data: { confirm: 'Are you sure you want to DELETE this Certificate?' } %>

    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-sm-6">
      <table class="table table-borderless table-sm">
        <thead>
        <tr>
          <th scope="col" style="width: 10%;"></th>
          <th scope="col" style="width: 90%;"></th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td><span class="font-weight-lighter">Speaker:</span></td>
          <td><span class="font-weight-normal"><%= @certificate.speaker %></span></td>
        </tr>
        <tr>
          <td><span class="font-weight-lighter">(eng)</span></td>
          <td><span class="font-weight-lighter"><%= @certificate.speaker_eng %></span></td>
        </tr>
        <tr>
          <td><span class="font-weight-lighter">Description:</span></td>
          <td><span class="font-weight-normal"><%= @certificate.description %></span></td>
        </tr>
        <tr>
          <td><span class="font-weight-lighter">(eng)</span></td>
          <td><span class="font-weight-lighter"><%= @certificate.description_eng %></span></td>
        </tr>
        <tr>
          <td><span class="font-weight-lighter">Date:</span></td>
          <td><span class="font-weight-normal"><%= @certificate.date.strftime('%d.%m.%y') %></span></td>
        </tr>
        <tr>
          <td><span class="font-weight-lighter">Filename:</span></td>
          <td><span class="font-weight-normal"><%= @certificate.name %></span></td>
        </tr>
        </tbody>
      </table>
    </div>
    <div class="col-sm-3">
      <div class="d-flex align-items-center justify-content-center" style="height: 36px">
        <h6 style="margin: 0">🇷🇺Rus template</h6>
        <% if @certificate.rus_template %>
          <div>
            <%= button_to '&#10007;'.html_safe, admin_rus_template_path(@rus_template), class: 'btn btn-outline-danger btn-sm ml-2', style: 'border: none', method: :delete, data: { confirm: 'Are you sure you want to DELETE this Rus template?' } if @rus_template%>
          </div>
        <% end %>
      </div>
      <div style="height: 80%">
        <% if @certificate.rus_template %>
          <div class="d-flex align-items-center justify-content-center mt-2">
            <%= image_tag @certificate.rus_template.pdf_file.url(:thumb) %>
          </div>
          <div class="d-flex justify-content-center ml-4">
            <table class="table table-borderless table-sm">
              <thead>
              <tr>
                <th scope="col" style="width: 40%;"></th>
                <th scope="col" style="width: 60%;"></th>
              </tr>
              </thead>
              <tbody>
              <tr>
                <td><span class="font-weight-lighter">Resolution:</span></td>
                <td><span class="font-weight-normal"><%= @certificate.rus_template.pdf_width %>х<%= @certificate.rus_template.pdf_height %></span></td>
              </tr>
              <tr>
                <td><span class="font-weight-lighter">Font size:</span></td>
                <td><span class="font-weight-normal"><%= @certificate.rus_template.font_size %></span></td>
              </tr>
              <tr>
                <td><span class="font-weight-lighter">Font color:</span></td>
                <td><span class="font-weight-normal"><%= @certificate.rus_template.font_color %></span></td>
              </tr>
              <tr>
                <td><span class="font-weight-lighter">X-pos:</span></td>
                <td><span class="font-weight-normal"><%= @certificate.rus_template.xpos %></span></td>
              </tr>
              <tr>
                <td><span class="font-weight-lighter">Y-pos:</span></td>
                <td><span class="font-weight-normal"><%= @certificate.rus_template.ypos %></span></td>
              </tr>
              </tbody>
            </table>
          </div>
          <div class="d-flex align-items-center justify-content-center">
            <%= link_to 'Edit', edit_admin_rus_template_path(@rus_template), class: "btn btn-outline-secondary btn-sm" %>
          </div>
      <% else %>
          <div class="d-flex align-items-center justify-content-center" style="height: 100%;">
            <%= link_to new_admin_rus_template_path(certificate_id: @certificate.id) do %>
              <button type="button" class="btn btn-outline-secondary" style="width: 6em; height: 6em; border: none;">
                <svg width="3em" height="3em" viewBox="0 0 16 16" class="bi bi-plus-circle-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z"/>
                </svg>
              </button>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-sm-3">

      <div class="d-flex align-items-center justify-content-center" style="height: 36px">
        <h6 style="margin: 0;">🇺🇸Eng template</h6>
        <% if @certificate.eng_template %>
          <div>
            <%= button_to '&#10007;'.html_safe, admin_eng_template_path(@eng_template), class: 'btn btn-outline-danger btn-sm ml-2', style: 'border: none', method: :delete, data: { confirm: 'Are you sure you want to DELETE this Eng template?' }%>
          </div>
        <% end %>
      </div>

      <div style="height: 80%">
        <% if @certificate.eng_template %>
          <div class="d-flex align-items-center justify-content-center mt-2">
            <%= image_tag @certificate.eng_template.pdf_file.url(:thumb) %>
          </div>
          <div class="d-flex justify-content-center ml-4">
            <table class="table table-borderless table-sm">
              <thead>
              <tr>
                <th scope="col" style="width: 40%;"></th>
                <th scope="col" style="width: 60%;"></th>
              </tr>
              </thead>
              <tbody>
              <tr>
                <td><span class="font-weight-lighter">Resolution:</span></td>
                <td><span class="font-weight-normal"><%= @certificate.eng_template.pdf_width %>х<%= @certificate.eng_template.pdf_height %></span></td>
              </tr>
              <tr>
                <td><span class="font-weight-lighter">Font size:</span></td>
                <td><span class="font-weight-normal"><%= @certificate.eng_template.font_size %></span></td>
              </tr>
              <tr>
                <td><span class="font-weight-lighter">Font color:</span></td>
                <td><span class="font-weight-normal"><%= @certificate.eng_template.font_color %></span></td>
              </tr>
              <tr>
                <td><span class="font-weight-lighter">X-pos:</span></td>
                <td><span class="font-weight-normal"><%= @certificate.eng_template.xpos %></span></td>
              </tr>
              <tr>
                <td><span class="font-weight-lighter">Y-pos:</span></td>
                <td><span class="font-weight-normal"><%= @certificate.eng_template.ypos %></span></td>
              </tr>
              </tbody>
            </table>
          </div>
          <div class="d-flex align-items-center justify-content-center">
            <%= link_to 'Edit', edit_admin_eng_template_path(@eng_template), class: "btn btn-outline-secondary btn-sm" %>
          </div>
        <% else %>
          <div class="d-flex align-items-center justify-content-center" style="height: 100%;">
            <%= link_to new_admin_eng_template_path(certificate_id: @certificate.id) do %>
              <button type="button" class="btn btn-outline-secondary" style="width: 6em; height: 6em; border: none;">
                <svg width="3em" height="3em" viewBox="0 0 16 16" class="bi bi-plus-circle-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z"/>
                </svg>
              </button>
            <% end %>
          </div>
        <% end %>
    </div>
    </div>
  </div>

  <hr>

  <%= link_to "All certificates", admin_certificates_path(), class: "btn btn-outline-secondary btn-sm" %>

</div>